"""Read-only derived query primitives."""

from .cards import (
    CardSemanticViewV1,
    QueryNotFoundV1,
    SemanticStateV1,
    card_name_lookup_key,
    semantic_state_for,
)
from .deck import (
    DECK_ANALYSIS_SCHEMA,
    DeckAmbiguousNameV1,
    DeckAnalysisV1,
    DeckCapabilityCountV1,
    DeckCardSummaryV1,
    DeckInputError,
    DeckInvalidLineV1,
    DeckInvalidReasonV1,
    DeckParsedEntryV1,
    DeckParseResultV1,
    DeckProvenanceTraceV1,
    DeckSectionAnalysisV1,
    DeckSectionV1,
    DeckUnknownNameV1,
    analyze_deck_bytes,
    analyze_deck_file,
    parse_deck_bytes,
)
from .details import (
    CapabilityDetailViewV1,
    CardDetailViewV1,
    CardIdentityV1,
    CardNameResolutionStatusV1,
    CardNameResolutionV1,
    MappedSubsetFrequencyV1,
    RequirementDetailViewV1,
)
from .indexes import (
    CARD_NAME_INDEX_SCHEMA,
    CARD_ORACLE_INDEX_SCHEMA,
    CARDS_BY_CAPABILITY_SCHEMA,
    LINKS_BY_REQUIREMENT_SCHEMA,
    REQUIREMENTS_BY_CARD_SCHEMA,
    DerivedIndexRowsV1,
    build_index_rows,
    validate_index_row,
)

__all__ = [
    "CARD_NAME_INDEX_SCHEMA",
    "CARD_ORACLE_INDEX_SCHEMA",
    "CARDS_BY_CAPABILITY_SCHEMA",
    "LINKS_BY_REQUIREMENT_SCHEMA",
    "REQUIREMENTS_BY_CARD_SCHEMA",
    "CardSemanticViewV1",
    "DECK_ANALYSIS_SCHEMA",
    "DeckAmbiguousNameV1",
    "DeckAnalysisV1",
    "DeckCapabilityCountV1",
    "DeckCardSummaryV1",
    "DeckInputError",
    "DeckInvalidLineV1",
    "DeckInvalidReasonV1",
    "DeckParseResultV1",
    "DeckParsedEntryV1",
    "DeckProvenanceTraceV1",
    "DeckSectionAnalysisV1",
    "DeckSectionV1",
    "DeckUnknownNameV1",
    "CardDetailViewV1",
    "CardIdentityV1",
    "CardNameResolutionStatusV1",
    "CardNameResolutionV1",
    "CapabilityDetailViewV1",
    "DerivedIndexRowsV1",
    "MappedSubsetFrequencyV1",
    "QueryNotFoundV1",
    "RequirementDetailViewV1",
    "SemanticStateV1",
    "build_index_rows",
    "card_name_lookup_key",
    "analyze_deck_bytes",
    "analyze_deck_file",
    "parse_deck_bytes",
    "semantic_state_for",
    "validate_index_row",
]
